/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Chinnu
 */
public class Adminstrator extends javax.swing.JFrame {
    Connection connect=null;
    ResultSet rst=null;
    PreparedStatement pst=null;

    /**
     * Creates new form Adminstrator
     */
    public Adminstrator() {
        initComponents();
        connect=(Connection)Course.connDB();
        this.setBounds(300, 100, 650, 370);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        jLabel1.setText("ADMINSTRATOR INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 410, 35);

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel2.setText("Admin_id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(185, 72, 94, 24);

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel3.setText("Admin_Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(185, 107, 94, 24);

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(185, 141, 94, 24);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(308, 72, 100, 24);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(308, 108, 100, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(308, 142, 100, 24);

        jButton1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(29, 216, 101, 29);

        jButton2.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(175, 216, 103, 29);

        jButton3.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(343, 216, 105, 29);

        jButton4.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton4.setText("DISPLAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(504, 216, 111, 29);

        jButton5.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(29, 11, 67, 23);

        jButton6.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton6.setText("DISPLAY RECORDS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(226, 272, 203, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/digital-wallpaper-1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-220, 0, 880, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/*try {
Statement s=connect.createStatement();
String sql = "insert into Adminstrator values('"+id.getText()+"','"+name.getText()+"','"+pass.getText()+"')";
s.executeUpdate(sql);
JOptionPane.showMessageDialog(null, "Success !");
id.setText(" ");
name.setText(" ");
pass.setText(" ");

}
catch (HeadlessException | SQLException e) {
System.out.println("errorrr");
}*/
CallableStatement cs;
try{
    Statement s=connect.createStatement();
    cs=connect.prepareCall("{ call add_admin(?,?,?)}");
    cs.setString("admin_id",jTextField1.getText());
    cs.setString("admin_name",jTextField2.getText());
    cs.setString("password",jTextField3.getText());
    cs.executeUpdate();
    JOptionPane.showMessageDialog(null, "Success !");
}
catch(SQLException ex)
        {
            Logger.getLogger(Adminstrator.class.getName()).log(Level.SEVERE,null,ex);
    
}
    
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try
{
    String sql1="delete from Enters where admin_id='"+jTextField1.getText()+"'";
Statement s1=connect.createStatement();
s1.executeUpdate(sql1);
String sql2="delete from Adds where admin_id='"+jTextField1.getText()+"'";
Statement s2=connect.createStatement();
s2.executeUpdate(sql2);
String sql="delete from Adminstrator where admin_id='"+jTextField1.getText()+"'";
Statement s=connect.createStatement();
s.executeUpdate(sql);
JOptionPane.showMessageDialog(null," Admin Records Deleted Succssfully... ");
jTextField1.setText("");
jTextField2.setText("");
jTextField1.requestFocusInWindow();
}
catch(Exception ee)
{
}// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
{
String sql="update Adminstrator set admin_name='"+jTextField2.getText()+ "',password='"+jTextField3.getText()+"' where admin_id='"+jTextField1.getText()+"'";
Statement s=connect.createStatement();
s.executeUpdate(sql);
JOptionPane.showMessageDialog(null," Adminstrator Records UPdated Succssfully... ");
jTextField1.setText("");
jTextField2.setText("");
jTextField1.requestFocusInWindow();
}
catch(Exception ee)
{
JOptionPane.showMessageDialog(null," Erro="+ee);
}        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try
{
String sql="select * from Adminstrator where admin_id='"+jTextField1.getText()+"'";
Statement s=connect.createStatement();
rst=s.executeQuery(sql);
if(rst.next()==false)
{
JOptionPane.showMessageDialog(null," No Such Records Invalid Aid");
jTextField1.setText("");
jTextField1.requestFocusInWindow();
}
else
{
jTextField2.setText(rst.getString(2));
jTextField3.setText(rst.getString(3));
}
}
catch(Exception ee)
{
}        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
setVisible(false);
Menu home=new Menu();
home.setVisible(true);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 tablemysql6 frame = new tablemysql6();
        frame.pack();
        frame.setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminstrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminstrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminstrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminstrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminstrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
